# action.yml
name: 'Cordova Build Engine'
description: 'Builds Cordova projects in a secure, encapsulated Docker environment.'
author: 'SwapLab Engine'

inputs:
  appBaseUrl:
    description: 'The base URL of the main application server.'
    required: true
  buildId:
    description: 'The unique ID for this build.'
    required: true
  userId:
    description: 'The ID of the user triggering the build.'
    required: true
  projectUrl:
    description: 'The R2 URL to download the project zip.'
    required: true
  buildType:
    description: 'The type of build (e.g., debug-apk, release-aab).'
    required: true
  keystoreUrl:
    description: 'URL for the release.jks file.'
    required: false
    default: ''
  keystorePassword:
    description: 'Password for the keystore.'
    required: false
    default: ''
  keyAlias:
    description: 'Alias for the key.'
    required: false
    default: ''
  keyPassword:
    description: 'Password for the key alias.'
    required: false
    default: ''
  webhookSecret:
    description: 'Secret for authenticating webhook calls.'
    required: true
  r2AccountId:
    description: 'Cloudflare R2 Account ID.'
    required: true
  r2AccessKeyId:
    description: 'Cloudflare R2 Access Key ID.'
    required: true
  r2SecretAccessKey:
    description: 'Cloudflare R2 Secret Access Key.'
    required: true
  r2BucketName:
    description: 'Cloudflare R2 Bucket Name.'
    required: true
  r2PublicUrl:
    description: 'The public URL for the R2 bucket.'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
