# Nama file: .circleci/config.yml (Versi Dinamis & Aman)
version: 2.1

parameters:
  appBaseUrl:
    type: string
    default: "" # <-- TAMBAHKAN INI
  buildId:
    type: string
    default: "" # <-- TAMBAHKAN INI
  buildToken:
    type: string
    default: "" # <-- TAMBAHKAN INI

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - setup_remote_docker:
          docker_layer_caching: true

      # Langkah 1 (BARU): Minta token ECR jangka pendek dari server Anda
      - run:
          name: Request short-lived ECR token
          command: |
            JSON_RESPONSE=$(curl -s -f -X POST \
              -H "Content-Type: application/json" \
              -d '{"buildId": "<< pipeline.parameters.buildId >>", "buildToken": "<< pipeline.parameters.buildToken >>"}' \
              "<< pipeline.parameters.appBaseUrl >>/api/request-ecr-token")
            
            # Ekstrak token dan URI dari respons JSON
            ECR_TOKEN=$(echo $JSON_RESPONSE | jq -r .ecrToken)
            REGISTRY_URI=$(echo $JSON_RESPONSE | jq -r .registryUri | sed 's|https://||') # Hapus https://

            if [ -z "$ECR_TOKEN" ] || [ "$ECR_TOKEN" == "null" ]; then
              echo "Failed to retrieve a valid ECR token."
              exit 1
            fi
            
            echo "Successfully retrieved ECR token."
            # Simpan token ke file agar bisa digunakan di langkah berikutnya
            echo "export ECR_TOKEN='$ECR_TOKEN'" >> $BASH_ENV
            echo "export REGISTRY_URI='$REGISTRY_URI'" >> $BASH_ENV

      # Langkah 2 (BARU): Login ke ECR menggunakan token dinamis
      - run:
          name: Log in to Amazon ECR
          command: |
            source $BASH_ENV
            # Decode token base64 dan pipe sebagai password ke docker login
            echo $ECR_TOKEN | base64 --decode | docker login --username AWS --password-stdin $REGISTRY_URI

      # Langkah 3: Jalankan Build Engine (tidak berubah)
      - run:
          name: Build Cordova Project via Secure Engine
          command: |
            source $BASH_ENV
            docker run --rm \
              -e INPUT_APPBASEURL="<< pipeline.parameters.appBaseUrl >>" \
              -e INPUT_BUILDID="<< pipeline.parameters.buildId >>" \
              -e INPUT_BUILDTOKEN="<< pipeline.parameters.buildToken >>" \
              -e CI_PROVIDER="circleci" \
              -e CIRCLE_WORKFLOW_ID=$CIRCLE_WORKFLOW_ID \
              -e CIRCLE_PROJECT_REPONAME=$CIRCLE_PROJECT_REPONAME \
              $REGISTRY_URI/swaplab/cordova-build-engine:main

workflows:
  build_app:
    jobs:
      - build
