# Nama file: .circleci/config.yml (Solusi Final dengan Caching Manual)
version: 2.1

parameters:
  appBaseUrl: { type: string, default: "" }
  buildId: { type: string, default: "" }
  buildToken: { type: string, default: "" }

jobs:
  build:
    # Menggunakan machine executor dengan image Ubuntu LTS yang sudah termasuk Docker.
    machine:
      image: ubuntu-2204:current
    
    steps:
      - checkout

      - restore_cache:
          keys:
            # Kunci ini akan mencoba mencari cache yang persis sama
            - v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            # Jika tidak ada, gunakan cache gradle terbaru
            - v1-gradle-wrapper-

      # Memulihkan file cache (docker-image.tar) dari build sebelumnya.
      - restore_cache:
          keys:
            - v1-docker-image-cache-main

      # Memuat image Docker dari file cache jika ada, untuk menghindari pull.
      - run:
          name: Load Docker Image from Cache
          command: |
            if [ -f /tmp/caches/docker-image.tar ]; then
              echo "✅ Cache ditemukan, memuat image Docker..."
              docker load < /tmp/caches/docker-image.tar
            else
              echo "⚠️ Cache tidak ditemukan, akan melakukan pull penuh."
            fi

      # Meminta token akses sementara ke ECR.
      - run:
          name: Request short-lived ECR token
          command: |
            JSON_RESPONSE=$(curl -s -f -X POST -H "Content-Type: application/json" -d '{"buildId": "<< pipeline.parameters.buildId >>", "buildToken": "<< pipeline.parameters.buildToken >>"}' "<< pipeline.parameters.appBaseUrl >>/api/request-ecr-token")
            ECR_TOKEN=$(echo $JSON_RESPONSE | jq -r .ecrToken)
            REGISTRY_URI=$(echo $JSON_RESPONSE | jq -r .registryUri | sed 's|https://||')
            if [ -z "$ECR_TOKEN" ] || [ "$ECR_TOKEN" == "null" ]; then exit 1; fi
            echo "export ECR_TOKEN='$ECR_TOKEN'" >> $BASH_ENV
            echo "export REGISTRY_URI='$REGISTRY_URI'" >> $BASH_ENV

      # Login ke Amazon ECR.
      - run:
          name: Log in to Amazon ECR
          command: |
            source $BASH_ENV
            echo $ECR_TOKEN | base64 --decode | cut -d: -f2 | docker login --username AWS --password-stdin $REGISTRY_URI

      # Menjalankan "kotak hitam". Docker akan cek image lokal dulu (dari cache) sebelum pull.
      - run:
          name: Run Secure Build Engine
          command: |
            source $BASH_ENV
            # Untuk keamanan, kita lakukan pull dengan flag --quiet untuk memastikan image terbaru.
            # Jika image sudah ada dari cache, proses ini akan sangat cepat.
            docker pull --quiet $REGISTRY_URI/swaplab/cordova-build-engine:main
            
            docker run --rm \
              -e INPUT_APPBASEURL="<< pipeline.parameters.appBaseUrl >>" \
              -e INPUT_BUILDID="<< pipeline.parameters.buildId >>" \
              -e INPUT_BUILDTOKEN="<< pipeline.parameters.buildToken >>" \
              -e GITHUB_SERVER_URL="https://github.com" \
              -e GITHUB_REPOSITORY="$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME" \
              -e GITHUB_RUN_ID=$CIRCLE_WORKFLOW_ID \
              $REGISTRY_URI/swaplab/cordova-build-engine:main

      # Menyimpan image Docker ke dalam file .tar untuk build berikutnya.
      - run:
          name: Save Docker Image to Cache
          command: |
            mkdir -p /tmp/caches
            docker save $REGISTRY_URI/swaplab/cordova-build-engine:main > /tmp/caches/docker-image.tar

      - save_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
      
      
      - save_cache:
          key: v1-docker-image-cache-main
          paths:
            - /tmp/caches

workflows:
  build_app:
    when: << pipeline.parameters.buildId >>
    jobs:
      - build
