name: Cordova Build
on:
  repository_dispatch:
    types: [trigger-build]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 8
    steps:
      # --- TAMBAHKAN LANGKAH CACHE DI SINI ---
      - name: Cache dependencies (npm and gradle)
        uses: actions/cache@v4
        with:
          path: .cache
          # Ganti dengan kunci statis. 'v1' bisa Anda ubah menjadi 'v2' nanti
          # jika Anda ingin membuat cache baru dari awal.
          key: ${{ runner.os }}-cordova-deps-v1
          restore-keys: |
            ${{ runner.os }}-cordova-deps-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: swaplab-engine
          password: ${{ secrets.GHCR_PULL_TOKEN }}

      - name: Build Cordova Project via Secure Engine
        uses: swaplab-engine/cordova-build-engine@main
        with:
          appBaseUrl: ${{ github.event.client_payload.appBaseUrl }}
          buildId: ${{ github.event.client_payload.buildId }}
          buildToken: ${{ github.event.client_payload.buildToken }}
