name: Cordova Build
on:
  repository_dispatch:
    types: [trigger-build]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 8
    steps:
      # --- TAMBAHKAN LANGKAH CACHE DI SINI ---
      - name: Cache dependencies (npm and gradle)
        uses: actions/cache@v4
        with:
          # Path yang akan di-cache, sesuai dengan yang Anda siapkan di entrypoint.sh
          path: .cache
          # Kunci unik untuk cache. Cache hanya akan dipulihkan jika kunci ini sama persis.
          # Jika package-lock.json berubah, kunci akan berubah dan cache baru dibuat.
          key: ${{ runner.os }}-cordova-${{ hashFiles('**/package-lock.json') }}
          # Kunci cadangan jika tidak ada cache yang cocok persis.
          restore-keys: |
            ${{ runner.os }}-cordova-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: swaplab-engine
          password: ${{ secrets.GHCR_PULL_TOKEN }}

      - name: Build Cordova Project via Secure Engine
        uses: swaplab-engine/cordova-build-engine@main
        with:
          appBaseUrl: ${{ github.event.client_payload.appBaseUrl }}
          buildId: ${{ github.event.client_payload.buildId }}
          buildToken: ${{ github.event.client_payload.buildToken }}
