# .github/workflows/build-cordova.yml

name: Build Cordova from Upload

on:
  repository_dispatch:
    types: [trigger-build]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      # Menggunakan Node.js versi 20 sesuai persyaratan terbaru
      - name: Set up Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Menggunakan Java Development Kit (JDK) versi 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Install Cordova CLI
        run: npm install -g cordova

      - name: Download and Unzip Project
        run: |
          ZIP_URL="${{ github.event.client_payload.url }}"
          echo "Downloading project from $ZIP_URL"
          
          curl -L --retry 5 --retry-delay 2 -o cordovaProject.zip "$ZIP_URL"
          
          mkdir cordova-project
          unzip cordovaProject.zip -d cordova-project
          
      - name: Build Cordova Project
        run: |
          cd cordova-project
          
          echo "Installing project dependencies..."
          npm install
          
          echo "Adding Android platform..."
          cordova platform add android
          
          echo "Building Android APK..."
          cordova build android

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-apk
          path: cordova-project/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk