name: Cordova Build
on:
  repository_dispatch:
    types: [trigger-build]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 8
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ./.cache/gradle
            ./.gradle/wrapper
          key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            gradle-cache-${{ runner.os }}-

      - name: Restore npm cache
        uses: actions/cache@v4
        with:
          path: ./.cache/npm
          key: npm-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-cache-${{ runner.os }}-

      - name: Show cache sizes (quick check)
        run: |
          echo "Gradle cache size (./.cache/gradle):"
          du -sh ./.cache/gradle || true
          echo "NPM cache size (./.cache/npm):"
          du -sh ./.cache/npm || true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: swaplab-engine
          password: ${{ secrets.GHCR_PULL_TOKEN }}

      - name: Build Cordova Project via Secure Engine
        uses: swaplab-engine/cordova-build-engine@main
        with:
          appBaseUrl: ${{ github.event.client_payload.appBaseUrl }}
          buildId: ${{ github.event.client_payload.buildId }}
          buildToken: ${{ github.event.client_payload.buildToken }}
