name: Cordova Build (Debug/Release APK/AAB)

on:
  repository_dispatch:
    types: [trigger-build]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: ${{ github.event.client_payload.timeoutMinutes || 8 }}

    outputs:
      outcome: ${{ steps.final_check.outputs.outcome }}

    steps:
      - name: Record start time
        shell: bash
        run: echo "start_time=$(date +%s)" >> $GITHUB_ENV

      - name: Report Build In Progress
        shell: bash
        run: |
          curl --fail -X POST \
            -H "Content-Type: application/json" \
            -H "X-Build-Secret: ${{ secrets.WEBHOOK_SECRET }}" \
            -d '{
              "buildId": "${{ github.event.client_payload.buildId }}",
              "userId": "${{ github.event.client_payload.userId }}",
              "status": "in_progress"
            }' \
            "${{ github.event.client_payload.internalApiUrl }}/api/github-webhook"

      - name: Set up Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Set up JDK 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Cache Gradle Wrapper & Caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-8.2.0-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-8.2.0-

      - name: Install Cordova CLI
        shell: bash
        run: npm install -g cordova

      - name: Download and Unzip Project
        shell: bash
        run: |
          ZIP_URL="${{ github.event.client_payload.projectUrl }}"
          curl -L -o cordovaProject.zip "$ZIP_URL"
          mkdir cordova-project
          unzip cordovaProject.zip -d cordova-project

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: |
            cordova-project/node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('cordova-project/package-lock.json', 'cordova-project/package.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Install Dependencies and Build Project
        id: cordova_build_step
        shell: bash
        run: |
          exec &> ../build_log.txt
          set -e
          
          cd cordova-project
          echo "--- Installing Project Dependencies ---"
          npm ci || npm install
          echo "--- Adding Android Platform (locked to Gradle 8.2.0) ---"
          cordova platform add android@latest
          echo "--- Starting Cordova Build ---"

          if [[ "${{ github.event.client_payload.buildType }}" == "debug-apk" ]]; then
            cordova build android --debug -- --gradleArg=--no-daemon --gradleArg=-Pandroid.useAndroidX=true
          else
            echo "--- Downloading Keystore for Release Build ---"
            KEYSTORE_URL="${{ github.event.client_payload.keystoreUrl }}"
            curl -L -o release.jks "$KEYSTORE_URL"
            
            PACKAGE_TYPE_FLAG=""
            if [[ "${{ github.event.client_payload.buildType }}" == "release-aab" ]]; then
              PACKAGE_TYPE_FLAG="--packageType=bundle"
            fi

            echo "--- Starting Release Build ---"
            cordova build android --release -- --gradleArg=--no-daemon \
              --keystore="release.jks" \
              --alias="${{ github.event.client_payload.keyAlias }}" \
              --storePassword="${{ github.event.client_payload.keystorePassword }}" \
              --password="${{ github.event.client_payload.keyPassword }}" \
              --gradleArg=-Pandroid.useAndroidX=true \
              $PACKAGE_TYPE_FLAG
          fi
          echo "--- Cordova Build Finished ---"

      - name: Setup SSH for SCP
        if: success()
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Upload Build File via SCP and Report Success
        if: success()
        shell: bash
        run: |
          USER_ID="${{ github.event.client_payload.userId }}"
          BUILD_ID="${{ github.event.client_payload.buildId }}"
          BUILD_TYPE="${{ github.event.client_payload.buildType }}"
          
          ARTIFACT_PATH=$(find cordova-project/platforms/android/app -name "*.aab" -o -name "*.apk" | head -n 1)
          if [ -z "$ARTIFACT_PATH" ]; then echo "::error::Build artifact not found!"; exit 1; fi
          
          if [[ "$BUILD_TYPE" == "debug-apk" ]]; then PREFIX="debug"; else PREFIX="release"; fi
          if [[ "$BUILD_TYPE" == "release-aab" ]]; then EXTENSION="aab"; else EXTENSION="apk"; fi
          NEW_FILENAME="${PREFIX}_${BUILD_ID}.${EXTENSION}"

          ssh -o StrictHostKeyChecking=no emi@84.46.248.72 "mkdir -p /home/emi/swaplab-project/apps/cordova-app/public/builds/$USER_ID"
          scp -o StrictHostKeyChecking=no "$ARTIFACT_PATH" emi@84.46.248.72:/home/emi/swaplab-project/apps/cordova-app/public/builds/$USER_ID/$NEW_FILENAME

          DOWNLOAD_URL="${{ github.event.client_payload.publicBaseUrl }}/builds/$USER_ID/$NEW_FILENAME"
          
          end_time=$(date +%s)
          duration=$((end_time - start_time))
          
          curl --fail -X POST \
            -H "Content-Type: application/json" \
            -H "X-Build-Secret: ${{ secrets.WEBHOOK_SECRET }}" \
            -d '{
              "buildId": "'"$BUILD_ID"'", "userId": "'"$USER_ID"'",
              "status": "complete", "durationSeconds": "'"$duration"'", "downloadUrl": "'"$DOWNLOAD_URL"'"
            }' \
            "${{ github.event.client_payload.internalApiUrl }}/api/github-webhook"

      - name: Upload Log File and Report Failure
        if: failure()
        shell: bash
        run: |
          INTERNAL_API_URL="${{ github.event.client_payload.internalApiUrl }}"
          if [ -z "$INTERNAL_API_URL" ]; then
             echo "::error::Fatal: internalApiUrl not received in payload. Cannot report failure."
             exit 1
          fi

          USER_ID="${{ github.event.client_payload.userId }}"
          BUILD_ID="${{ github.event.client_payload.buildId }}"
          
          LOG_FILE_PATH="build_log.txt"
          if [ ! -f "${LOG_FILE_PATH}" ]; then
            echo "Build failed very early. Main log file not found." > ${LOG_FILE_PATH}
          fi
          
          UPLOAD_RESPONSE=$(curl -s -w "\n%{http_code}" -X POST -F "logFile=@${LOG_FILE_PATH}" -F "buildId=$BUILD_ID" -H "X-Build-Secret: ${{ secrets.WEBHOOK_SECRET }}" "$INTERNAL_API_URL/upload-log/$USER_ID")
          LOG_FILENAME=$(echo "$UPLOAD_RESPONSE" | sed '$d')
          LOG_SNIPPET=$(tail -n 50 ${LOG_FILE_PATH})
          CLEANED_LOG_SNIPPET=$(echo "$LOG_SNIPPET" | sed -E 's|/home/runner/work/[^/]+/[^/]+|[...]|g')
          ESCAPED_LOG_SNIPPET=$(echo "$CLEANED_LOG_SNIPPET" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g' | awk "{printf \"%s\\\\n\", \$0}" | sed 's/$/\\n/' | tr -d '\n')
          end_time=$(date +%s)
          duration=$((end_time - start_time))
          
          curl --fail -X POST -H "Content-Type: application/json" -H "X-Build-Secret: ${{ secrets.WEBHOOK_SECRET }}" -d '{"buildId": "'"$BUILD_ID"'", "userId": "'"$USER_ID"'","status": "failed", "durationSeconds": "'"$duration"'", "logFile": "'"$LOG_FILENAME"'","logSnippet": "'"$ESCAPED_LOG_SNIPPET"'"}' "$INTERNAL_API_URL/api/github-webhook"

      - name: Final check
        id: final_check
        if: always()
        shell: bash
        run: |
          echo "outcome=${{ job.status }}" >> $GITHUB_OUTPUT
