name: Capacitor Android Build (Debug/Release APK/AAB)

on:
  repository_dispatch:
    types: [trigger-build]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # ambil timeout dari client_payload
    timeout-minutes: ${{ github.event.client_payload.timeoutMinutes }}

    env:
      # default gradle version jika client_payload.gradleVersion tidak disediakan
      DEFAULT_GRADLE_VERSION: "8.7.0"

    steps:
      - name: Dump client_payload to log
        run: echo "${{ toJSON(github.event.client_payload) }}"

      - name: Set up Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # -------------------------
      # CACHE: npm global (keuntungan pada instalasi global)
      - name: Cache global npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-global-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-global-

      - name: Download and Unzip Project
        run: |
          ZIP_URL="${{ github.event.client_payload.projectUrl }}"
          curl -L -o project.zip "$ZIP_URL"
          mkdir app
          unzip -q project.zip -d app

      # -------------------------
      # CACHE: project node_modules (key berdasarkan package-lock.json)
      - name: Cache project node_modules
        uses: actions/cache@v4
        with:
          path: app/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('app/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install project dependencies
        working-directory: app
        run: |
          echo "Installing project dependencies..."
          npm ci

      - name: Build web assets (if present) and ensure Capacitor deps
        working-directory: app
        run: |
          npm run build --if-present

          # install local @capacitor/cli jika tidak ada
          if ! node -e "require('fs').existsSync('node_modules/@capacitor/cli')"; then
            npm install --no-audit --no-fund --save-dev @capacitor/cli @capacitor/core @capacitor/android
          fi

      # -------------------------
      # LOCK Gradle wrapper version (non-destructive, only for CI run)
      # dapat diberikan via client_payload.gradleVersion, mis: "8.4.1"
      - name: Lock Gradle Wrapper Version (CI-only)
        working-directory: app
        run: |
          set -e
          GRADLE_VERSION="${{ github.event.client_payload.gradleVersion || env.DEFAULT_GRADLE_VERSION }}"
          PROPERTIES_FILE="android/gradle/wrapper/gradle-wrapper.properties"

          if [ -f "$PROPERTIES_FILE" ]; then
            echo "Setting Gradle distribution to $GRADLE_VERSION in $PROPERTIES_FILE (CI-only change)"
            # replace distributionUrl line
            sed -i.bak -E "s|distributionUrl=.*|distributionUrl=https\\://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-all.zip|g" "$PROPERTIES_FILE"
            echo "Updated gradle-wrapper.properties:"
            grep distributionUrl "$PROPERTIES_FILE" || true
          else
            echo "No gradle-wrapper.properties found (skipping lock). If android project missing, npx cap add android will create wrapper."
          fi

      # -------------------------
      # CACHE: Gradle wrapper zip & related caches
      - name: Cache Gradle wrapper & Gradle caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            app/android/.gradle
          # key includes package-lock AND gradle-wrapper.properties hash so cache invalidates when gradle version or deps change
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('app/package-lock.json', 'app/android/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-cache-

      # -------------------------
      # CACHE: Maven local (~/.m2) & Android build-cache (optional, saves downloads)
      - name: Cache Maven repo and Android local cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.android/build-cache
          key: ${{ runner.os }}-maven-android-${{ hashFiles('app/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-maven-android-

      - name: Add / Sync Android native project (only if missing or to update)
        working-directory: app
        run: |
          if [ ! -d "./android" ]; then
            npx cap add android
          fi
          npx cap sync android
          ls -la android || true

        - name: Prepare Signing Keystore (release builds only)
        # hanya jalan kalau buildType mengindikasikan release
        if: ${{ contains(fromJson(toJSON(github.event.client_payload)).buildType, 'release') }}
        working-directory: app
        run: |
          set -e
          cd android
          KEYSTORE_URL="${{ github.event.client_payload.keystoreUrl || '' }}"

          if [ -z "$KEYSTORE_URL" ]; then
            echo "::error::Keystore URL not provided but buildType is release. Provide client_payload.keystoreUrl"
            exit 1
          fi

          echo "Downloading keystore..."
          curl -L -o release.jks "$KEYSTORE_URL"
          chmod 600 release.jks
          cd ..

      - name: Build Android (Gradle)
        working-directory: app
        run: |
          set -e
          cd android
          chmod +x ./gradlew || true

          BUILD_TYPE_RAW="${{ github.event.client_payload.buildType || 'debug' }}"
          # normalisasi: lower-case, hapus spasi
          BUILD_TYPE=$(echo "$BUILD_TYPE_RAW" | tr '[:upper:]' '[:lower:]' | tr -d ' ')

          echo "Normalized build type: $BUILD_TYPE"
          # tempatkan log gradle sehingga step failure dapat meng-upload
          LOG_FILE="$(pwd)/build_log.txt"
          echo "Gradle output will be saved to: $LOG_FILE"

          # helper: apakah ini debug?
          if [[ "$BUILD_TYPE" == debug* ]]; then
            echo "Running debug build (assembleDebug) ..."
            ./gradlew assembleDebug --no-daemon > "$LOG_FILE" 2>&1 || (tail -n 200 "$LOG_FILE" && exit 1)
            exit 0
          fi

          # pastikan untuk release: harus ada keystore jika build.gradle mengharapkan file
          if [[ "$BUILD_TYPE" == *release* ]]; then
            if [ ! -f "./release.jks" ]; then
              echo "::error::release.jks not found in android/ — ensure keystore was downloaded or provide keystoreUrl in payload"
              # dump last 200 lines dari log jika ada
              [ -f "$LOG_FILE" ] && tail -n 200 "$LOG_FILE" || true
              exit 1
            fi

            STORE="./release.jks"
            STORE_PASS="${{ github.event.client_payload.keystorePassword || '' }}"
            KEY_ALIAS="${{ github.event.client_payload.keyAlias || '' }}"
            KEY_PASS="${{ github.event.client_payload.keyPassword || '' }}"

            if [[ "$BUILD_TYPE" == *aab* || "$BUILD_TYPE" == *bundle* ]]; then
              echo "Building AAB (bundleRelease) ..."
              ./gradlew bundleRelease --no-daemon \
                -Pandroid.injected.signing.store.file="$STORE" \
                -Pandroid.injected.signing.store.password="$STORE_PASS" \
                -Pandroid.injected.signing.key.alias="$KEY_ALIAS" \
                -Pandroid.injected.signing.key.password="$KEY_PASS" > "$LOG_FILE" 2>&1 || (tail -n 200 "$LOG_FILE" && exit 1)
            else
              echo "Building Release APK (assembleRelease) ..."
              ./gradlew assembleRelease --no-daemon \
                -Pandroid.injected.signing.store.file="$STORE" \
                -Pandroid.injected.signing.store.password="$STORE_PASS" \
                -Pandroid.injected.signing.key.alias="$KEY_ALIAS" \
                -Pandroid.injected.signing.key.password="$KEY_PASS" > "$LOG_FILE" 2>&1 || (tail -n 200 "$LOG_FILE" && exit 1)
            fi

            exit 0
          fi

          # fallback safety
          echo "::error::Unknown buildType: $BUILD_TYPE_RAW"
          exit 1

      - name: Upload Build File to Your Server
        if: success()
        run: |
          BUILD_TYPE_RAW="${{ github.event.client_payload.buildType || 'debug' }}"
          BUILD_TYPE=$(echo "$BUILD_TYPE_RAW" | tr '[:upper:]' '[:lower:]' | tr -d ' ')
          USER_ID="${{ github.event.client_payload.userId }}"
          ARTIFACT_PATH=""

          if [[ "$BUILD_TYPE" == *aab* || "$BUILD_TYPE" == *bundle* ]]; then
            ARTIFACT_PATH=$(find app/android/app/build/outputs/bundle/release -name "*.aab" | head -n 1)
          elif [[ "$BUILD_TYPE" == debug* ]]; then
            ARTIFACT_PATH=$(find app/android/app/build/outputs/apk/debug -name "*.apk" | head -n 1)
          else
            ARTIFACT_PATH=$(find app/android/app/build/outputs/apk/release -name "*.apk" | head -n 1)
          fi

          if [ -z "$ARTIFACT_PATH" ]; then
            echo "::error::Build artifact not found!"
            exit 1
          fi

          echo "Uploading $ARTIFACT_PATH ..."
          curl -X POST \
            -F "buildFile=@$ARTIFACT_PATH" \
            -F "buildId=${{ github.event.client_payload.buildId }}" \
            -F "buildType=$BUILD_TYPE_RAW" \
            -H "X-Build-Secret: ${{ secrets.WEBHOOK_SECRET }}" \
            https://cordova.build.appjs.net/upload-result/$USER_ID

      - name: Filter and Upload Error Log
        if: failure()
        run: |
          USER_ID="${{ github.event.client_payload.userId }}"
          # prioritas: android build log, fallback ke app/build_log.txt
          LOG_FILE=""
          if [ -f "app/android/build_log.txt" ]; then
            LOG_FILE="app/android/build_log.txt"
          elif [ -f "app/android/build/outputs/**/*.log" ]; then
            LOG_FILE=$(find app/android -type f -name "*.log" | head -n 1)
          elif [ -f "app/build_log.txt" ]; then
            LOG_FILE="app/build_log.txt"
          else
            LOG_FILE=""
          fi

          if [ -z "$LOG_FILE" ]; then
            echo "No build log found; creating minimal log..."
            echo "Build gagal pada tahap awal atau tidak ada log lengkap." > build_log_fallback.txt
            LOG_FILE="build_log_fallback.txt"
          fi

          echo "Filtering sensitive information from $LOG_FILE ..."
          REDACTED_LOG_FILE="build_log_redacted.txt"

          sed \
            -e 's|https?://cordova\.build\.appjs\.net[^ ]*|[User_privacy_security_PATH_is_hidden]|g' \
            -e 's|/home/runner/work/[^ ]*|[User_privacy_security_PATH_is_hidden]|g' \
            -e 's|/opt/hostedtoolcache/[^ ]*|[User_privacy_security_PATH_is_hidden]|g' \
            -e 's|[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}|[User_privacy_security_PATH_is_hidden]|g' \
            "$LOG_FILE" > "$REDACTED_LOG_FILE"

          echo "Uploading redacted error log to server..."
          curl -X POST \
            -F "logFile=@$REDACTED_LOG_FILE" \
            -F "buildId=${{ github.event.client_payload.buildId }}" \
            -H "X-Build-Secret: ${{ secrets.WEBHOOK_SECRET }}" \
            https://cordova.build.appjs.net/upload-log/$USER_ID
