# File: .github/workflows/build-cordova.yml (Final dan Lengkap)

name: Cordova Build

on:
  repository_dispatch:
    types: [trigger-build]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    timeout-minutes: 8
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ./.cache/gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Cache global npm packages
        uses: actions/cache@v4
        with:
          path: ./.cache/npm
          key: ${{ runner.os }}-npm-global-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-global-
            
      - name: Build Cordova Project via Secure Engine
        uses: swaplab-engine/cordova-build-engine@main
        with:
          # --- Payload Data ---
          appBaseUrl: ${{ github.event.client_payload.appBaseUrl }}
          buildId: ${{ github.event.client_payload.buildId }}
          userId: ${{ github.event.client_payload.userId }}
          projectUrl: ${{ github.event.client_payload.projectUrl }}
          buildType: ${{ github.event.client_payload.buildType }}
          keystoreUrl: ${{ github.event.client_payload.keystoreUrl }}

          # --- Secrets ---
          keystorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyAlias: ${{ secrets.KEY_ALIAS }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          webhookSecret: ${{ secrets.WEBHOOK_SECRET }}
          r2AccountId: ${{ secrets.R2_ACCOUNT_ID }}
          r2AccessKeyId: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2SecretAccessKey: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2BucketName: ${{ secrets.R2_BUCKET_NAME }}
          r2PublicUrl: ${{ secrets.R2_PUBLIC_URL }}
