# .github/workflows/cordova-build.yml

name: Cordova Build
on:
  repository_dispatch:
    types: [trigger-build]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 8
    steps:
      # Langkah 1: Checkout kode (diperlukan untuk workspace)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Langkah 2: Login ke GHCR dengan PAT
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: swaplab-engine
          password: ${{ secrets.GHCR_PULL_TOKEN }} # PAT yang Anda sediakan
      
      # Langkah 3: Jalankan image privat Anda secara manual
      - name: Build Cordova Project via Secure Engine
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/github/workspace" \
            -w /github/workspace \
            -e INPUT_APPBASEURL="${{ github.event.client_payload.appBaseUrl }}" \
            -e INPUT_BUILDID="${{ github.event.client_payload.buildId }}" \
            -e INPUT_USERID="${{ github.event.client_payload.userId }}" \
            -e INPUT_PROJECTURL="${{ github.event.client_payload.projectUrl }}" \
            -e INPUT_BUILDTYPE="${{ github.event.client_payload.buildType }}" \
            -e INPUT_KEYSTOREURL="${{ github.event.client_payload.keystoreUrl }}" \
            -e INPUT_KEYSTOREPASSWORD="${{ secrets.KEYSTORE_PASSWORD }}" \
            -e INPUT_KEYALIAS="${{ secrets.KEY_ALIAS }}" \
            -e INPUT_KEYPASSWORD="${{ secrets.KEY_PASSWORD }}" \
            -e INPUT_WEBHOOKSECRET="${{ secrets.WEBHOOK_SECRET }}" \
            -e INPUT_R2ACCOUNTID="${{ secrets.R2_ACCOUNT_ID }}" \
            -e INPUT_R2ACCESSKEYID="${{ secrets.R2_ACCESS_KEY_ID }}" \
            -e INPUT_R2SECRETACCESSKEY="${{ secrets.R2_SECRET_ACCESS_KEY }}" \
            -e INPUT_R2BUCKETNAME="${{ secrets.R2_BUCKET_NAME }}" \
            -e INPUT_R2PUBLICURL="${{ secrets.R2_PUBLIC_URL }}" \
            -e INPUT_GITHUBJOBURL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            ghcr.io/swaplab-engine/cordova-build-engine:main
         
          
