name: Cordova Build (Debug/Release APK/AAB)

on:
  repository_dispatch:
    types: [trigger-build]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: ${{ github.event.client_payload.timeoutMinutes || 8 }}

    outputs:
      outcome: ${{ steps.final_check.outputs.outcome }}

    steps:
      - name: Record start time
        shell: bash
        run: echo "start_time=$(date +%s)" >> $GITHUB_ENV

      - name: Report Build In Progress
        shell: bash
        run: |
          curl --fail -X POST \
            -H "Content-Type: application/json" \
            -H "X-Build-Secret: ${{ secrets.WEBHOOK_SECRET }}" \
            -d '{
              "buildId": "${{ github.event.client_payload.buildId }}",
              "userId": "${{ github.event.client_payload.userId }}",
              "status": "in_progress"
            }' \
            "${{ github.event.client_payload.appBaseUrl }}/api/github-webhook"

      - name: Set up Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache global npm packages
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-global-v3

      - name: Install Cordova CLI
        shell: bash
        run: npm install -g cordova

      - name: Download and Unzip Project
        shell: bash
        run: |
          ZIP_URL="${{ github.event.client_payload.projectUrl }}"
          curl -L -o cordovaProject.zip "$ZIP_URL"
          mkdir cordova-project
          unzip cordovaProject.zip -d cordova-project

      - name: Prepare Signing Configuration
        if: ${{ startsWith(github.event.client_payload.buildType, 'release') }}
        shell: bash
        run: |
          cd cordova-project
          KEYSTORE_URL="${{ github.event.client_payload.keystoreUrl }}"
          curl -L -o release.jks "$KEYSTORE_URL"
          PACKAGE_TYPE="apk"
          if [[ "${{ github.event.client_payload.buildType }}" == "release-aab" ]]; then
            PACKAGE_TYPE="bundle"
          fi
          cat > build.json << EOF
          { "android": { "release": { "keystore": "release.jks", "storePassword": "${{ github.event.client_payload.keystorePassword }}", "alias": "${{ github.event.client_payload.keyAlias }}", "password": "${{ github.event.client_payload.keyPassword }}", "packageType": "$PACKAGE_TYPE" } } }
          EOF

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('cordova-project/**/gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Install Dependencies and Build Project
        id: cordova_build_step
        shell: bash
        run: |
          cd cordova-project
          {
            echo "--- Installing Project Dependencies ---"
            npm install
            echo "--- Adding Android Platform ---"
            cordova platform add android
            echo "--- Starting Cordova Build ---"
            if [[ "${{ github.event.client_payload.buildType }}" == "debug-apk" ]]; then
              cordova build android --debug -- --gradleArg=--no-daemon
            else
              cordova build android --release --buildConfig=build.json -- --gradleArg=--no-daemon
            fi
            echo "--- Cordova Build Finished ---"
          } > ../build_log.txt 2>&1

# ===================================================================
# [PERUBAHAN DIMULAI DI SINI] - Langkah upload lama dihapus
# ===================================================================

      - name: Upload Artifact to GitHub
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-${{ github.event.client_payload.buildId }}
          path: |
            cordova-project/platforms/android/app/build/outputs/apk/debug/*.apk
            cordova-project/platforms/android/app/build/outputs/apk/release/*.apk
            cordova-project/platforms/android/app/build/outputs/bundle/release/*.aab
          if-no-files-found: error
          retention-days: 7

      - name: Report Success to Server
        if: success()
        shell: bash
        run: |
          end_time=$(date +%s)
          duration=$((end_time - start_time))
          
          # Mengirim notifikasi ke server bahwa build selesai, tanpa menyertakan file.
          # URL download sekarang merujuk ke halaman artefak GitHub.
          curl --fail -X POST \
            -H "Content-Type: application/json" \
            -H "X-Build-Secret: ${{ secrets.WEBHOOK_SECRET }}" \
            -d '{
              "buildId": "${{ github.event.client_payload.buildId }}", 
              "userId": "${{ github.event.client_payload.userId }}",
              "status": "complete", 
              "durationSeconds": "'"$duration"'", 
              "downloadUrl": "See GitHub Actions artifacts for download."
            }' \
            "${{ github.event.client_payload.appBaseUrl }}/api/github-webhook"

# ===================================================================
# [PERUBAHAN SELESAI] - Langkah upload log tetap sama
# ===================================================================

      - name: Upload Log File and Report Failure
        if: failure()
        shell: bash
        run: |
          USER_ID="${{ github.event.client_payload.userId }}"
          APP_BASE_URL="${{ github.event.client_payload.appBaseUrl }}"
          BUILD_ID="${{ github.event.client_payload.buildId }}"

          LOG_FILE_PATH="build_log.txt"
          if [ -f "cordova-project/build_log.txt" ]; then
            cp cordova-project/build_log.txt ./${LOG_FILE_PATH}
          elif [ ! -f "${LOG_FILE_PATH}" ]; then
            echo "Build gagal pada tahap sangat awal. File log utama tidak ditemukan." > ${LOG_FILE_PATH}
          fi

          UPLOAD_RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
            -F "logFile=@${LOG_FILE_PATH}" \
            -F "buildId=$BUILD_ID" \
            -H "X-Build-Secret: ${{ secrets.WEBHOOK_SECRET }}" \
            "$APP_BASE_URL/upload-log/$USER_ID")
          
          HTTP_CODE=$(echo "$UPLOAD_RESPONSE" | tail -n1)
          LOG_FILENAME=$(echo "$UPLOAD_RESPONSE" | sed '$d') 
          
          LOG_SNIPPET=$(tail -n 50 ${LOG_FILE_PATH})
          
          CLEANED_LOG_SNIPPET=$(echo "$LOG_SNIPPET" | sed -E 's|/home/runner/work/[^/]+/[^/]+|[...]|g')
          
          CLEANED_LOG_SNIPPET=$(echo "$CLEANED_LOG_SNIPPET" | sed -E "s|${APP_BASE_URL}/uploads/[^ ]+|[PROTECTED_URL]|g")
          CLEANED_LOG_SNIPPET=$(echo "$CLEANED_LOG_SNIPPET" | sed -E "s|${APP_BASE_URL}/keystore/[^ ]+|[PROTECTED_URL]|g")
          
          ESCAPED_LOG_SNIPPET=$(echo "$CLEANED_LOG_SNIPPET" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g' | awk '{printf "%s\\n", $0}' | sed 's/$/\\n/' | tr -d '\n')

          end_time=$(date +%s)
          duration=$((end_time - start_time))

          curl --fail -X POST \
            -H "Content-Type: application/json" \
            -H "X-Build-Secret: ${{ secrets.WEBHOOK_SECRET }}" \
            -d '{
              "buildId": "'"$BUILD_ID"'", 
              "userId": "'"$USER_ID"'",
              "status": "failed", 
              "durationSeconds": "'"$duration"'", 
              "logFile": "'"$LOG_FILENAME"'",
              "logSnippet": "'"$ESCAPED_LOG_SNIPPET"'"
            }' \
            "${{ github.event.client_payload.appBaseUrl }}/api/github-webhook"

      - name: Final check
        id: final_check
        if: always()
        shell: bash
        run: |
          echo "outcome=${{ job.status }}" >> $GITHUB_OUTPUT
