name: Cordova Build (Debug/Release APK/AAB)

on:
  repository_dispatch:
    types: [trigger-build]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    timeout-minutes: ${{ github.event.client_payload.timeoutMinutes }}

    steps:
      - name: Dump client_payload to log
        run: echo "${{ toJSON(github.event.client_payload) }}"

      # BARU: Catat waktu mulai build untuk menghitung durasi
      - name: Record start time
        run: echo "start_time=$(date +%s)" >> $GITHUB_ENV

      - name: Set up Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache global npm packages
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-global-v1
          restore-keys: |
            ${{ runner.os }}-npm-global-

      - name: Install Cordova CLI
        run: npm install -g cordova

      - name: Download and Unzip Project
        run: |
          ZIP_URL="${{ github.event.client_payload.projectUrl }}"
          curl -L -o cordovaProject.zip "$ZIP_URL"
          mkdir cordova-project
          unzip cordovaProject.zip -d cordova-project

      - name: Cache project dependencies (node_modules)
        uses: actions/cache@v4
        with:
          path: cordova-project/node_modules
          key: ${{ runner.os }}-npm-project-${{ hashFiles('cordova-project/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-project-

      - name: Prepare Signing Configuration
        run: |
          cd cordova-project
          KEYSTORE_URL="${{ github.event.client_payload.keystoreUrl }}"
          curl -L -o release.jks "$KEYSTORE_URL"
          PACKAGE_TYPE="apk"
          if [[ "${{ github.event.client_payload.buildType }}" == "release-aab" ]]; then
            PACKAGE_TYPE="bundle"
          fi
          cat > build.json << EOF
          {
            "android": { "release": { "keystore": "release.jks", "storePassword": "${{ github.event.client_payload.keystorePassword }}", "alias": "${{ github.event.client_payload.keyAlias }}", "password": "${{ github.event.client_payload.keyPassword }}", "packageType": "$PACKAGE_TYPE" } }
          }
          EOF

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('cordova-project/**/*.gradle*', 'cordova-project/**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Dependencies and Build Project
        run: |
          cd cordova-project
          {
            echo "Installing project dependencies..."
            npm install
            
            echo "Building Cordova project..."
            cordova platform add android
            cordova build android --release --buildConfig=build.json -- --gradleArg=--no-daemon
          } > build_log.txt 2>&1

      - name: Upload Build File to Your Server
        if: success()
        run: |
          BUILD_TYPE="${{ github.event.client_payload.buildType }}"
          USER_ID="${{ github.event.client_payload.userId }}"
          ARTIFACT_PATH=""
          if [[ "$BUILD_TYPE" == "release-aab" ]]; then
            ARTIFACT_PATH=$(find cordova-project/platforms/android/app/build/outputs/bundle/release -name "*.aab" | head -n 1)
          else
            ARTIFACT_PATH=$(find cordova-project/platforms/android/app/build/outputs/apk/release -name "*.apk" | head -n 1)
          fi
          if [ -z "$ARTIFACT_PATH" ]; then
            echo "::error::Build artifact not found!"
            exit 1
          fi
          curl -X POST \
            -F "buildFile=@$ARTIFACT_PATH" \
            -F "buildId=${{ github.event.client_payload.buildId }}" \
            -F "buildType=$BUILD_TYPE" \
            -H "X-Build-Secret: ${{ secrets.WEBHOOK_SECRET }}" \
            https://cordova.build.appjs.net/upload-result/$USER_ID

      - name: Filter and Upload Error Log
        if: failure()
        run: |
          USER_ID="${{ github.event.client_payload.userId }}"
          LOG_FILE="cordova-project/build_log.txt"
          REDACTED_LOG_FILE="cordova-project/build_log_redacted.txt"

          if [ ! -f "$LOG_FILE" ]; then
            echo "Build gagal pada tahap sangat awal." > "$LOG_FILE"
          fi
          
          echo "Filtering sensitive information from log file..."
          
          sed \
            -e 's|https?://cordova\.build\.appjs\.net[^ ]*|[User_privacy_security_PATH_is_hidden]|g' \
            -e 's|/home/runner/work/[^ ]*|[User_privacy_security_PATH_is_hidden]|g' \
            -e 's|/opt/hostedtoolcache/[^ ]*|[User_privacy_security_PATH_is_hidden]|g' \
            -e 's|[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}|[User_privacy_security_PATH_is_hidden]|g' \
            "$LOG_FILE" > "$REDACTED_LOG_FILE"

          echo "Uploading redacted error log to server..."
          curl -X POST \
            -F "logFile=@$REDACTED_LOG_FILE" \
            -F "buildId=${{ github.event.client_payload.buildId }}" \
            -H "X-Build-Secret: ${{ secrets.WEBHOOK_SECRET }}" \
            https://cordova.build.appjs.net/upload-log/$USER_ID

      # BARU: Laporkan status akhir dan durasi build
      - name: Report Build Duration and Status
        if: always() # Pastikan langkah ini selalu berjalan, baik sukses maupun gagal
        run: |
          end_time=$(date +%s)
          duration=$((end_time - start_time))
          USER_ID="${{ github.event.client_payload.userId }}"

          echo "Reporting final status: ${{ job.status }} after ${duration} seconds."
          
          curl -X POST \
            -F "buildId=${{ github.event.client_payload.buildId }}" \
            -F "userId=$USER_ID" \
            -F "durationSeconds=$duration" \
            -F "status=${{ job.status }}" \
            -H "X-Build-Secret: ${{ secrets.WEBHOOK_SECRET }}" \
            https://cordova.build.appjs.net/report-duration
