name: Cordova Build
on:
  repository_dispatch:
    types: [trigger-build]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 8
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print computed cache keys (debug)
        run: |
          echo "Computed gradle cache key:"
          echo "gradle-cache-${{ runner.os }}-gradle-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties','**/platforms/android/**/build.gradle*','**/package-lock.json') }}"
          echo "Computed npm cache key:"
          echo "npm-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}"

      - name: Restore Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ./.cache/gradle
            ./.gradle/wrapper
          key: gradle-cache-${{ runner.os }}-gradle-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties','**/platforms/android/**/build.gradle*','**/package-lock.json') }}
          restore-keys: |
            gradle-cache-${{ runner.os }}-gradle-


      - name: Restore npm cache
        uses: actions/cache@v4
        with:
          path: ./.cache/npm
          key: npm-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-cache-${{ runner.os }}-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: swaplab-engine
          password: ${{ secrets.GHCR_PULL_TOKEN }}

      - name: Build Cordova Project via Secure Engine
        uses: swaplab-engine/cordova-build-engine@main
        with:
          appBaseUrl: ${{ github.event.client_payload.appBaseUrl }}
          buildId: ${{ github.event.client_payload.buildId }}
          buildToken: ${{ github.event.client_payload.buildToken }}

      - name: Debug: show gradle cache AFTER build
        if: always()
        run: |
          echo "ls -la ./.cache/gradle || true"
          ls -la ./.cache/gradle || true
          echo "du -sh ./.cache/gradle || true"
          du -sh ./.cache/gradle || true
