name: Cordova Build
on:
  repository_dispatch:
    types: [trigger-build]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 8
    steps:

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: swaplab-engine
          password: ${{ secrets.GHCR_PULL_TOKEN }}

      - name: Build Cordova Project via Secure Engine
        uses: swaplab-engine/cordova-build-engine@main
        with:
          appBaseUrl: ${{ github.event.client_payload.appBaseUrl }}
          buildId: ${{ github.event.client_payload.buildId }}
          buildToken: ${{ github.event.client_payload.buildToken }}
