# .github/workflows/build-cordova.yml

name: Build and Upload DEBUG APK

on:
  repository_dispatch:
    types: [trigger-build]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Izin 'write' tidak lagi diperlukan

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Cordova CLI
        run: npm install -g cordova

      - name: Download and Unzip Project
        run: |
          ZIP_URL="${{ github.event.client_payload.url }}"
          curl -L --retry 5 --retry-delay 2 -o cordovaProject.zip "$ZIP_URL"
          mkdir cordova-project
          unzip cordovaProject.zip -d cordova-project

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('cordova-project/**/*.gradle*', 'cordova-project/**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Debug APK
        run: |
          cd cordova-project
          npm install
          cordova platform add android
          cordova build android -- --gradleArg=--no-daemon

      # --- PERUBAHAN UTAMA: Ganti 'Create Release' dengan 'Upload to Server' ---
      - name: Upload APK to Your Server
        run: |
          # Temukan path file APK
          APK_PATH=$(find cordova-project/platforms/android/app/build/outputs/apk/debug -name "*.apk" | head -n 1)
          echo "Uploading $APK_PATH to server..."
          
          # Gunakan curl untuk mengirim file sebagai multipart/form-data
          curl -X POST \
            -F "apkFile=@$APK_PATH" \
            -F "buildId=${{ github.event.client_payload.buildId }}" \
            -H "X-Build-Secret: ${{ secrets.WEBHOOK_SECRET }}" \
            https://cordova.build.appjs.net/upload-result
