name: Cordova Build (Debug/Release APK/AAB)

on:
  repository_dispatch:
    types: [trigger-build]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: ${{ github.event.client_payload.timeoutMinutes || 8 }}

    # ID ini penting untuk referensi di langkah terakhir
    outputs:
      outcome: ${{ steps.final_check.outputs.outcome }}

    steps:
      - name: Record start time
        shell: bash
        run: echo "start_time=$(date +%s)" >> $GITHUB_ENV

      - name: Report Build In Progress
        shell: bash
        run: |
          curl --fail -X POST \
            -H "Content-Type: application/json" \
            -H "X-Build-Secret: ${{ secrets.WEBHOOK_SECRET }}" \
            -d '{
              "buildId": "${{ github.event.client_payload.buildId }}",
              "userId": "${{ github.event.client_payload.userId }}",
              "status": "in_progress"
            }' \
            "${{ github.event.client_payload.appBaseUrl }}/api/github-webhook"

      - name: Set up Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache global npm packages
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-global-v3

      - name: Install Cordova CLI
        shell: bash
        run: npm install -g cordova

      - name: Download and Unzip Project
        shell: bash
        run: |
          ZIP_URL="${{ github.event.client_payload.projectUrl }}"
          curl -L -o cordovaProject.zip "$ZIP_URL"
          mkdir cordova-project
          unzip cordovaProject.zip -d cordova-project

      - name: Prepare Signing Configuration
        if: ${{ startsWith(github.event.client_payload.buildType, 'release') }}
        shell: bash
        run: |
          cd cordova-project
          KEYSTORE_URL="${{ github.event.client_payload.keystoreUrl }}"
          curl -L -o release.jks "$KEYSTORE_URL"
          PACKAGE_TYPE="apk"
          if [[ "${{ github.event.client_payload.buildType }}" == "release-aab" ]]; then
            PACKAGE_TYPE="bundle"
          fi
          cat > build.json << EOF
          { "android": { "release": { "keystore": "release.jks", "storePassword": "${{ github.event.client_payload.keystorePassword }}", "alias": "${{ github.event.client_payload.keyAlias }}", "password": "${{ github.event.client_payload.keyPassword }}", "packageType": "$PACKAGE_TYPE" } } }
          EOF

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('cordova-project/**/gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Install Dependencies and Build Project
        id: cordova_build_step
        shell: bash
        run: |
          cd cordova-project
          {
            echo "--- Installing Project Dependencies ---"
            npm install
            echo "--- Adding Android Platform ---"
            cordova platform add android
            echo "--- Starting Cordova Build ---"
            if [[ "${{ github.event.client_payload.buildType }}" == "debug-apk" ]]; then
              cordova build android --debug -- --gradleArg=--no-daemon
            else
              cordova build android --release --buildConfig=build.json -- --gradleArg=--no-daemon
            fi
            echo "--- Cordova Build Finished ---"
          } > ../build_log.txt 2>&1

      - name: Upload Build File and Report Success
        if: success()
        shell: bash
        run: |
          BUILD_TYPE="${{ github.event.client_payload.buildType }}"
          USER_ID="${{ github.event.client_payload.userId }}"
          APP_BASE_URL="${{ github.event.client_payload.appBaseUrl }}"

          ARTIFACT_PATH=""
          if [[ "$BUILD_TYPE" == "release-aab" ]]; then
            ARTIFACT_PATH=$(find cordova-project/platforms/android/app/build/outputs/bundle/release -name "*.aab" | head -n 1)
          elif [[ "$BUILD_TYPE" == "release-apk" ]]; then
            ARTIFACT_PATH=$(find cordova-project/platforms/android/app/build/outputs/apk/release -name "*.apk" | head -n 1)
          else
            ARTIFACT_PATH=$(find cordova-project/platforms/android/app/build/outputs/apk/debug -name "*.apk" | head -n 1)
          fi

          if [ -z "$ARTIFACT_PATH" ]; then echo "::error::Build artifact not found!"; exit 1; fi

          UPLOAD_RESPONSE=$(curl -s -w "\n%{http_code}" --fail -X POST \
            -F "buildFile=@$ARTIFACT_PATH" \
            -F "buildId=${{ github.event.client_payload.buildId }}" \
            -F "buildType=$BUILD_TYPE" \
            -H "X-Build-Secret: ${{ secrets.WEBHOOK_SECRET }}" \
            "$APP_BASE_URL/upload-result/$USER_ID")

          HTTP_CODE=$(echo "$UPLOAD_RESPONSE" | tail -n1)
          DOWNLOAD_URL=$(echo "$UPLOAD_RESPONSE" | sed '$d')

          if [[ "$HTTP_CODE" != "200" ]]; then echo "::error::Gagal upload. Kode: $HTTP_CODE"; exit 1; fi

          end_time=$(date +%s)
          duration=$((end_time - start_time))

          curl --fail -X POST \
            -H "Content-Type: application/json" \
            -H "X-Build-Secret: ${{ secrets.WEBHOOK_SECRET }}" \
            -d '{
              "buildId": "${{ github.event.client_payload.buildId }}", "userId": "'"$USER_ID"'",
              "status": "complete", "durationSeconds": "'"$duration"'", "downloadUrl": "'"$DOWNLOAD_URL"'"
            }' \
            "$APP_BASE_URL/api/github-webhook"

      - name: Upload Log File and Report Failure
        if: failure()
        shell: bash
        run: |
          USER_ID="${{ github.event.client_payload.userId }}"
          APP_BASE_URL="${{ github.event.client_payload.appBaseUrl }}"
          BUILD_ID="${{ github.event.client_payload.buildId }}"

          LOG_FILE_PATH="build_log.txt"
          if [ -f "cordova-project/build_log.txt" ]; then
            cp cordova-project/build_log.txt ./${LOG_FILE_PATH}
          elif [ ! -f "${LOG_FILE_PATH}" ]; then
            echo "Build gagal pada tahap sangat awal. File log utama tidak ditemukan." > ${LOG_FILE_PATH}
          fi

          # Upload file log lengkap untuk admin
          UPLOAD_RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
            -F "logFile=@${LOG_FILE_PATH}" \
            -F "buildId=$BUILD_ID" \
            -H "X-Build-Secret: ${{ secrets.WEBHOOK_SECRET }}" \
            "$APP_BASE_URL/upload-log/$USER_ID")
          
          HTTP_CODE=$(echo "$UPLOAD_RESPONSE" | tail -n1)
          LOG_FILENAME=$(echo "$UPLOAD_RESPONSE" | sed '$d') 
          
          # Ekstrak 50 baris terakhir log sebagai cuplikan
          LOG_SNIPPET=$(tail -n 50 ${LOG_FILE_PATH})
          
          # ==========================================================
          # ===== [PERBAIKAN] Saring path sensitif dari log snippet =====
          # ==========================================================
          # Ganti path absolut runner GitHub Actions dengan placeholder
          CLEANED_LOG_SNIPPET=$(echo "$LOG_SNIPPET" | sed -E 's|/home/runner/work/[^/]+/[^/]+|[...]|g')
          
          # [FIX] Pecah satu perintah 'sed' kompleks menjadi dua perintah sederhana
          # Saring URL uploads
          CLEANED_LOG_SNIPPET=$(echo "$CLEANED_LOG_SNIPPET" | sed -E "s|${APP_BASE_URL}/uploads/[^ ]+|[PROTECTED_URL]|g")
          # Saring URL keystore
          CLEANED_LOG_SNIPPET=$(echo "$CLEANED_LOG_SNIPPET" | sed -E "s|${APP_BASE_URL}/keystore/[^ ]+|[PROTECTED_URL]|g")
          # ==========================================================
          
          # Escape karakter khusus dari snippet yang sudah dibersihkan
          ESCAPED_LOG_SNIPPET=$(echo "$CLEANED_LOG_SNIPPET" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g' | awk '{printf "%s\\n", $0}' | sed 's/$/\\n/' | tr -d '\n')

          end_time=$(date +%s)
          duration=$((end_time - start_time))

          # Kirim 'logSnippet' yang sudah bersih dan di-escape ke server.js
          curl --fail -X POST \
            -H "Content-Type: application/json" \
            -H "X-Build-Secret: ${{ secrets.WEBHOOK_SECRET }}" \
            -d '{
              "buildId": "'"$BUILD_ID"'", 
              "userId": "'"$USER_ID"'",
              "status": "failed", 
              "durationSeconds": "'"$duration"'", 
              "logFile": "'"$LOG_FILENAME"'",
              "logSnippet": "'"$ESCAPED_LOG_SNIPPET"'"
            }' \
            "$APP_BASE_URL/api/github-webhook"

      - name: Final check
        id: final_check
        if: always()
        shell: bash
        run: |
          # job.status tersedia sebagai ekspresi GitHub Actions; tulis ke GITHUB_OUTPUT supaya dapat dipakai sebagai output job
          echo "outcome=${{ job.status }}" >> $GITHUB_OUTPUT
