name: Cordova Build (Debug/Release APK/AAB)

on:
  repository_dispatch:
    types: [trigger-build]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: ${{ github.event.client_payload.timeoutMinutes || 8 }}

    outputs:
      outcome: ${{ steps.final_check.outputs.outcome }}

    steps:
      # ... (semua langkah dari awal sampai build project tetap sama) ...
      - name: Record start time
        shell: bash
        run: echo "start_time=$(date +%s)" >> $GITHUB_ENV

      - name: Report Build In Progress
        shell: bash
        run: |
          curl --fail -X POST \
            -H "Content-Type: application/json" \
            -H "X-Build-Secret: ${{ secrets.WEBHOOK_SECRET }}" \
            -d '{
              "buildId": "${{ github.event.client_payload.buildId }}",
              "userId": "${{ github.event.client_payload.userId }}",
              "status": "in_progress"
            }' \
            "${{ github.event.client_payload.internalApiUrl }}/api/github-webhook"

      - name: Set up Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache global npm packages
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-global-v3

      - name: Install Cordova CLI
        shell: bash
        run: npm install -g cordova

      - name: Download and Unzip Project
        shell: bash
        run: |
          ZIP_URL="${{ github.event.client_payload.projectUrl }}"
          curl -L -o cordovaProject.zip "$ZIP_URL"
          mkdir cordova-project
          unzip cordovaProject.zip -d cordova-project

      - name: Prepare Signing Configuration
        if: ${{ startsWith(github.event.client_payload.buildType, 'release') }}
        shell: bash
        run: |
          cd cordova-project
          KEYSTORE_URL="${{ github.event.client_payload.keystoreUrl }}"
          curl -L -o release.jks "$KEYSTORE_URL"
          PACKAGE_TYPE="apk"
          if [[ "${{ github.event.client_payload.buildType }}" == "release-aab" ]]; then
            PACKAGE_TYPE="bundle"
          fi
          cat > build.json << EOF
          { "android": { "release": { "keystore": "release.jks", "storePassword": "${{ github.event.client_payload.keystorePassword }}", "alias": "${{ github.event.client_payload.keyAlias }}", "password": "${{ github.event.client_payload.keyPassword }}", "packageType": "$PACKAGE_TYPE" } } }
          EOF

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('cordova-project/**/gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Install Dependencies and Build Project
        id: cordova_build_step
        shell: bash
        run: |
          cd cordova-project
          {
            echo "--- Installing Project Dependencies ---"
            npm install
            echo "--- Adding Android Platform ---"
            cordova platform add android
            echo "--- Starting Cordova Build ---"
            if [[ "${{ github.event.client_payload.buildType }}" == "debug-apk" ]]; then
              cordova build android --debug -- --gradleArg=--no-daemon
            else
              cordova build android --release --buildConfig=build.json -- --gradleArg=--no-daemon
            fi
            echo "--- Cordova Build Finished ---"
          } > ../build_log.txt 2>&1

      - name: Setup SSH for SCP
        if: success()
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Upload Build File via SCP and Report Success
        if: success()
        shell: bash
        run: |
          # --- Bagian 1: Temukan file dan buat nama file baru (tidak berubah) ---
          BUILD_TYPE="${{ github.event.client_payload.buildType }}"
          USER_ID="${{ github.event.client_payload.userId }}"
          BUILD_ID="${{ github.event.client_payload.buildId }}"

          ARTIFACT_PATH=""
          if [[ "$BUILD_TYPE" == "release-aab" ]]; then
            ARTIFACT_PATH=$(find cordova-project/platforms/android/app/build/outputs/bundle/release -name "*.aab" | head -n 1)
          elif [[ "$BUILD_TYPE" == "release-apk" ]]; then
            ARTIFACT_PATH=$(find cordova-project/platforms/android/app/build/outputs/apk/release -name "*.apk" | head -n 1)
          else
            ARTIFACT_PATH=$(find cordova-project/platforms/android/app/build/outputs/apk/debug -name "*.apk" | head -n 1)
          fi
          
          if [ -z "$ARTIFACT_PATH" ]; then echo "::error::Build artifact not found!"; exit 1; fi
          
          if [[ "$BUILD_TYPE" == "debug-apk" ]]; then PREFIX="debug"; else PREFIX="release"; fi
          if [[ "$BUILD_TYPE" == "release-aab" ]]; then EXTENSION="aab"; else EXTENSION="apk"; fi
          NEW_FILENAME="${PREFIX}_${BUILD_ID}.${EXTENSION}"

          # ===================================================================
          # [LOGIKA BARU] Pastikan direktori user ada di server sebelum upload
          # ===================================================================
          echo "Ensuring user directory exists on server..."
          ssh -o StrictHostKeyChecking=no emi@84.46.248.72 "mkdir -p /home/emi/swaplab-project/apps/cordova-app/public/builds/$USER_ID"

          # --- Bagian 2: Unggah file menggunakan SCP (tidak berubah) ---
          echo "Uploading to server as $NEW_FILENAME..."
          scp -o StrictHostKeyChecking=no "$ARTIFACT_PATH" emi@84.46.248.72:/home/emi/swaplab-project/apps/cordova-app/public/builds/$USER_ID/$NEW_FILENAME
          echo "Upload complete."

          # --- Bagian 3: Laporkan status sukses ke server (tidak berubah) ---
          DOWNLOAD_URL="${{ github.event.client_payload.publicBaseUrl }}/builds/$USER_ID/$NEW_FILENAME"
          
          end_time=$(date +%s)
          duration=$((end_time - start_time))
          
          curl --fail -X POST \
            -H "Content-Type: application/json" \
            -H "X-Build-Secret: ${{ secrets.WEBHOOK_SECRET }}" \
            -d '{
              "buildId": "'"$BUILD_ID"'", "userId": "'"$USER_ID"'",
              "status": "complete", "durationSeconds": "'"$duration"'", "downloadUrl": "'"$DOWNLOAD_URL"'"
            }' \
            "${{ github.event.client_payload.internalApiUrl }}/api/github-webhook"

      - name: Upload Log File and Report Failure
        if: failure()
        shell: bash
        run: |
          # ... (Langkah ini tidak berubah, sudah menggunakan URL internal) ...
          USER_ID="${{ github.event.client_payload.userId }}"
          INTERNAL_API_URL="${{ github.event.client_payload.internalApiUrl }}"
          BUILD_ID="${{ github.event.client_payload.buildId }}"

          LOG_FILE_PATH="build_log.txt"
          if [ ! -f "build_log.txt" ]; then
             echo "Build log not found at root. Checking in project dir..."
             if [ -f "cordova-project/build_log.txt" ]; then
                cp cordova-project/build_log.txt ./${LOG_FILE_PATH}
             elif [ ! -f "${LOG_FILE_PATH}" ]; then
                echo "Build failed very early. Main log file not found." > ${LOG_FILE_PATH}
             fi
          fi

          UPLOAD_RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
            -F "logFile=@${LOG_FILE_PATH}" \
            -F "buildId=$BUILD_ID" \
            -H "X-Build-secret: ${{ secrets.WEBHOOK_SECRET }}" \
            "$INTERNAL_API_URL/upload-log/$USER_ID")

          LOG_FILENAME=$(echo "$UPLOAD_RESPONSE" | sed '$d')

          LOG_SNIPPET=$(tail -n 50 ${LOG_FILE_PATH})
          
          CLEANED_LOG_SNIPPET=$(echo "$LOG_SNIPPET" | sed -E 's|/home/runner/work/[^/]+/[^/]+|[...]|g' | sed -E "s|${{ github.event.client_payload.publicBaseUrl }}/[^ ]+|[PROTECTED_URL]|g")

          ESCAPED_LOG_SNIPPET=$(echo "$CLEANED_LOG_SNIPPET" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g' | awk '{printf "%s\\n", $0}' | sed 's/$/\\n/' | tr -d '\n')
          
          end_time=$(date +%s)
          duration=$((end_time - start_time))

          curl --fail -X POST \
            -H "Content-Type: application/json" \
            -H "X-Build-Secret: ${{ secrets.WEBHOOK_SECRET }}" \
            -d '{
              "buildId": "'"$BUILD_ID"'", 
              "userId": "'"$USER_ID"'",
              "status": "failed", 
              "durationSeconds": "'"$duration"'", 
              "logFile": "'"$LOG_FILENAME"'",
              "logSnippet": "'"$ESCAPED_LOG_SNIPPET"'"
            }' \
            "${{ github.event.client_payload.internalApiUrl }}/api/github-webhook"

      - name: Final check
        id: final_check
        if: always()
        shell: bash
        run: |
          echo "outcome=${{ job.status }}" >> $GITHUB_OUTPUT
