# Nama file: .github/workflows/cordova-build.yml
# Versi Final Profesional (Tanpa Secret Manual)

name: Cordova Build Service

on:
  workflow_dispatch:
    inputs:
      appBaseUrl:
        required: true
      buildId:
        required: true
      buildToken:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      # Langkah 1 (BARU): Meminta token sementara dari server Anda
      - name: Get Temporary Checkout Token
        id: get_token
        run: |
          TOKEN_JSON=$(curl -sS -f -X POST \
            -H "Authorization: Bearer ${{ github.event.inputs.buildToken }}" \
            -H "Content-Type: application/json" \
            -d '{"buildId": "${{ github.event.inputs.buildId }}"}' \
            "${{ github.event.inputs.appBaseUrl }}/api/github/get-checkout-token")
          
          TEMP_TOKEN=$(echo $TOKEN_JSON | jq -r '.token')
          
          if [ -z "$TEMP_TOKEN" ] || [ "$TEMP_TOKEN" == "null" ]; then
            echo "::error::Failed to retrieve a temporary checkout token from the build server."
            exit 1
          fi
          
          echo "token=${TEMP_TOKEN}" >> $GITHUB_OUTPUT

      # Langkah 2: Checkout repositori privat menggunakan token sementara
      - name: Checkout Private Build Engine
        uses: actions/checkout@v4
        with:
          repository: swaplab-engine/cordova-build-engine
          token: ${{ steps.get_token.outputs.token }} # Menggunakan token dari langkah sebelumnya
          path: '.github/actions/build-engine'

      # Langkah 3: Login ke GHCR (tetap sama)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Langkah 4: Jalankan action dari path lokal (tetap sama)
      - name: Build Cordova Project via Secure Engine
        uses: ./.github/actions/build-engine
        with:
          appBaseUrl: ${{ github.event.inputs.appBaseUrl }}
          buildId: ${{ github.event.inputs.buildId }}
          buildToken: ${{ github.event.inputs.buildToken }}
